source 'https://rubygems.org'

gem 'rails', '3.2.12'
gem 'pg'
gem 'bootstrap-sass', '2.3.1.0'
gem 'bcrypt-ruby', '3.0.1'
gem 'faker', '1.0.1'
gem 'will_paginate', '3.0.3'
gem 'bootstrap-will_paginate', '0.0.6'
gem 'jquery-rails', '2.0.2'
gem 'execjs'
#gem 'therubyracer'
gem 'sys-proctable'
gem 'passenger', '4.0.0.rc4'
gem 'activerecord-reputation-system', require: 'reputation_system'
gem 'rails_12factor', group: :production

group :development, :test do
  gem 'annotate', '2.5.0'
  gem 'rspec-rails', '2.11.0'
  gem 'guard-rspec', '1.2.1'
  gem 'guard-spork', '1.2.0'  
  gem 'spork', '0.9.2'
  
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '3.2.5'
  gem 'coffee-rails', '3.2.2'
  gem 'uglifier', '1.2.3'
end

group :test do
  gem 'capybara', '1.1.2'
  gem 'factory_girl_rails', '4.1.0'
  # gem 'cucumber-rails', '1.2.1', :require => false
  # gem 'database_cleaner', '0.7.0'
  gem 'launchy', '2.1.0'
  platforms :mswin, :mingw do  #Windows!
    gem "wdm", "~> 0.1"
    gem 'rb-fchange', '0.0.5'
    gem 'rb-notifu', '0.0.4'
    gem 'win32console', '1.3.0'
  end
  # gem 'rb-fsevent', '0.9.1', :require => false
  # gem 'growl', '1.0.3'
end
